### ISSUE TITLE
Support for fish shell?

### ISSUE THREAD

**Issue by schovi** [pawurb/lazyme#2]
Is it even possible? I know you can show history via `history` command, but I was not able to find a file with data.

**Comment by pawurb** [comment]
Looks like there is one https://github.com/fish-shell/fish-shell/issues/862 . I've seen it has a bit different structure so would require some additional parsing. I will not have time to look into it but PR's are welcome.

**Comment by schovi** [comment]
@pawurb I looks like YAML. Which should be easy to parse :)

**Comment by schovi** [comment]
Immediately reach invalid yaml

```
- cmd: git commit -m "CircleCI: cache gems"
  when: 1515704493
```

Problem is `:`. Whole content of `cmd:` should be wrap to `"` and quotes inside should be escaped. Will open issue in fish shell

**Comment by pawurb** [comment]
I think you could just parse it line by line, and extract info that's needed. Sth like:
```
commands = lines.lazy.select do |line| line.include?("cmd:") end.map do |line| line.split(" ").last end
```

**Comment by schovi** [comment]
@pawurb As quick win, sure. Will try tommorow.
There is related fish issue https://github.com/fish-shell/fish-shell/issues/4675

**Comment by schovi** [comment]
@pawurb There is one big problem that history is de-duplicated. Seems like impossible task :) Close this and just write it to Readme?

**Comment by pawurb** [comment]
It does not report the same commands provided one after other, but does save duplicates:
```
- cmd: ls
  when: 1516527345
- cmd: cat ~/.local/share/fish/fish_history
  when: 1516527347
- cmd: la
  when: 1516527355
- cmd: ls
  when: 1516527356
- cmd: la
  when: 1516527356
```

It still would make sense to do it imho

**Comment by schovi** [comment]
@pawurb In my history file there is no duplications at all. I made working solution and found it in result of lazyme table which was empty (except 3 truncated commands longer than limit)
